-- Static route metadata for the CTA system.
insert into public.transit_routes (route_id, mode, name, color) values
  ('Red',  'train', 'Red Line',    '#C60C30'),
  ('Blue', 'train', 'Blue Line',   '#00A1DE'),
  ('Brn',  'train', 'Brown Line',  '#62361B'),
  ('G',    'train', 'Green Line',  '#009B3A'),
  ('Org',  'train', 'Orange Line', '#F9461C'),
  ('P',    'train', 'Purple Line', '#522398'),
  ('Pink', 'train', 'Pink Line',   '#E27EA6'),
  ('Y',    'train', 'Yellow Line', '#F9E300'),
  ('3',   'bus', '#3 King Drive',                       '#2E7D32'),
  ('4',   'bus', '#4 Cottage Grove',                    '#2E7D32'),
  ('6',   'bus', '#6 Jackson Park Express',             '#2E7D32'),
  ('8',   'bus', '#8 Halsted',                          '#2E7D32'),
  ('9',   'bus', '#9 Ashland',                          '#2E7D32'),
  ('12',  'bus', '#12 Roosevelt',                       '#2E7D32'),
  ('20',  'bus', '#20 Madison',                         '#2E7D32'),
  ('22',  'bus', '#22 Clark',                           '#2E7D32'),
  ('36',  'bus', '#36 Broadway',                        '#2E7D32'),
  ('49',  'bus', '#49 Western',                         '#2E7D32'),
  ('53',  'bus', '#53 Pulaski',                         '#2E7D32'),
  ('63',  'bus', '#63 63rd',                            '#2E7D32'),
  ('66',  'bus', '#66 Chicago',                         '#2E7D32'),
  ('77',  'bus', '#77 Belmont',                         '#2E7D32'),
  ('79',  'bus', '#79 79th',                            '#2E7D32'),
  ('81',  'bus', '#81 Lawrence',                        '#2E7D32'),
  ('82',  'bus', '#82 Kimball-Homan',                   '#2E7D32'),
  ('146', 'bus', '#146 Inner Drive/Michigan Express',   '#2E7D32'),
  ('147', 'bus', '#147 Outer DuSable Lake Shore Exp',   '#2E7D32'),
  ('151', 'bus', '#151 Sheridan',                       '#2E7D32')
on conflict (route_id) do update
  set mode = excluded.mode,
      name = excluded.name,
      color = excluded.color;
